apiVersion: v1
kind: Namespace
metadata:
  name: udp-tracer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: udp-tracer
  namespace: udp-tracer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udp-tracer
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: udp-tracer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: udp-tracer
subjects:
  - kind: ServiceAccount
    name: udp-tracer
    namespace: udp-tracer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-tracer
  namespace: udp-tracer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-tracer
  template:
    metadata:
      labels:
        app: udp-tracer
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: udp-tracer
      nodeSelector:
        kubernetes.io/hostname: "kind-control-plane"  # Replace with the correct node
      containers:
        - name: udp-tracer
          image: maheshrayas/udp-tracer:v0.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - CAP_BPF
            privileged: true
            readOnlyRootFilesystem: true
          env:
            - name: RUST_LOG
              value: INFO
            - name: CURRENT_NODE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /sys/kernel/debug
              name: debugfs
              readOnly: false
            - name: bpffs
              mountPath: /sys/fs/bpf
              readOnly: true
            - mountPath: /sys/kernel/tracing
              name: tracefs
              readOnly: true
            - mountPath: /proc
              name: hostproc
              readOnly: true
            - mountPath: /run/containerd/io.containerd.runtime.v2.task
              name: run-containerd-bundle
              readOnly: true
            - mountPath: /run/containerd/containerd.sock
              name: containerd-sock
              readOnly: true
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
            type: Directory
        - name: tracefs
          hostPath:
            path: /sys/kernel/tracing
            type: Directory
        - name: hostproc
          hostPath:
            path: /proc
            type: Directory
        - hostPath:
            path: /run/containerd/io.containerd.runtime.v2.task
            type: ""
          name: run-containerd-bundle
        - hostPath:
            path: /run/containerd/containerd.sock
            type: ""
          name: containerd-sock
    